---
title: "Candlestick and Trends"
author: "The Algebros"
date: "2024-03-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
clf <- read.csv("/Users/ulyssesdu/Downloads/CLF_data_1.csv")
dal <- read.csv("/Users/ulyssesdu/Downloads/DAL_data_1.csv")
merged_data <- merge(clf, dal, by = "Date")
```


```{r}
clf$Date <- as.Date(clf$Date, format="%Y-%m-%d")

clf$Open <- as.numeric(clf$Open)
clf$Close <- as.numeric(clf$Close)

dal$Date <- as.Date(dal$Date, format="%Y-%m-%d")

dal$Open <- as.numeric(dal$Open)
dal$Close <- as.numeric(dal$Close)

plot(clf$Date, clf$Open, type = 'l', main = 'Open Price Over Time', xlab = 'Date', ylab = 'Open Price', col = 'blue')

plot(clf$Date, clf$Close, type = 'l', main = 'Close Price Over Time', xlab = 'Date', ylab = 'Close Price', col = 'blue')

plot(dal$Date, dal$Open, type = 'l', main = 'Open Price Over Time', xlab = 'Date', ylab = 'Open Price', col = 'red')

plot(dal$Date, dal$Close, type = 'l', main = 'Close Price Over Time', xlab = 'Date', ylab = 'Close Price', col = 'red')

```

```{r}
y_min <- floor(min(c(min(clf$Open), min(dal$Open))))
y_max <- ceiling(max(c(max(clf$Open), max(dal$Open))))

x_min <- min(c(min(clf$Date), min(dal$Date)))
x_max <- max(c(max(clf$Date), max(dal$Date)))

plot(clf$Date, clf$Open, type = 'l', col = 'blue', lwd = 2,
     xlim = c(x_min, x_max), ylim = c(y_min, y_max),
     xlab = "Date", ylab = "Open Price", main = "Open Prices Comparison",
     xaxt = 'n') 


lines(dal$Date, dal$Open, type = 'l', col = 'red', lwd = 2)

```
```{r}
y_min1 <- floor(min(c(min(clf$Close), min(dal$Close))))
y_max1 <- ceiling(max(c(max(clf$Close), max(dal$Close))))

x_min1 <- min(c(min(clf$Date), min(dal$Date)))
x_max1 <- max(c(max(clf$Date), max(dal$Date)))

plot(clf$Date, clf$Close, type = 'l', col = 'blue', lwd = 2,
     xlim = c(x_min1, x_max1), ylim = c(y_min1, y_max1),
     xlab = "Date", ylab = "Close Price", main = "Close Prices Comparison",
     xaxt = 'n') 


lines(dal$Date, dal$Close, type = 'l', col = 'red', lwd = 2)

```


### Candlesticks Chart
```{r}
library(quantmod)

chartSeries(clf, type = "candlesticks",theme = chartTheme("white"))
chartSeries(dal, type = "candlesticks",theme = chartTheme("white"))

```

```{r}
library(dplyr)

merged_data$delta_C <- merged_data$Close.x - merged_data$Open.x
merged_data$delta_D <- merged_data$Close.y - merged_data$Open.y

merged_data$delta_C_squared <- merged_data$delta_C^2
merged_data$delta_D_squared <- merged_data$delta_D^2

merged_data$lag_delta_C <- dplyr::lag(merged_data$delta_C,1)
merged_data$lag_delta_D <- dplyr::lag(merged_data$delta_D,1)

merged_data$lag_delta_C_squared <- dplyr::lag(merged_data$delta_C_squared,1)
merged_data$lag_delta_D_squared <- dplyr::lag(merged_data$delta_D_squared,1)

merged_data$lag2_delta_C_squared <- dplyr::lag(merged_data$delta_C_squared,2)
merged_data$lag2_delta_D_squared <- dplyr::lag(merged_data$delta_D_squared,2)

merged_data$lag3_delta_C_squared <- dplyr::lag(merged_data$delta_C_squared,3)
merged_data$lag3_delta_D_squared <- dplyr::lag(merged_data$delta_D_squared,3)
 
merged_data$lag4_delta_C_squared <- dplyr::lag(merged_data$delta_C_squared,4)
merged_data$lag4_delta_D_squared <- dplyr::lag(merged_data$delta_D_squared,4)

write.csv(merged_data, "/Users/ulyssesdu/Downloads/Merged_data.csv")
```






