---
title: "Untitled"
output: html_document
date: "2024-03-30"
---

```{r setup, include=FALSE}
library(dplyr)
library(AER)
library(dynlm)
library(forecast)
library(readxl)
library(stargazer)
library(scales)
library(quantmod)
library(urca)
```

## R Markdown


```{r data import}
Merged_data <- read_csv("Merged_data.csv", 
     col_types = cols(Date = col_date(format = "%Y-%m-%d")))

Merged_data$delta_D_high <- Merged_data$High.y - Merged_data$Open.y
Merged_data$delta_C_high <- Merged_data$High.x- Merged_data$Open.x
```

## Including Plots


```{r regressions}
summary(Merged_data)

FlexMom_Dl <- lm(delta_D ~  lag_delta_D + lag_delta_D_squared + lag2_delta_D_squared,data = Merged_data)
FlexMom_high_Dl <- lm(delta_D_high ~  lag_delta_D + lag_delta_D_squared + lag2_delta_D_squared,data = Merged_data)

summary(FlexMom_Dl)

summary(FlexMom_high_Dl)

FlexMom_Cr <- lm(delta_C ~  lag_delta_C + lag_delta_C_squared + lag2_delta_C_squared,data = Merged_data)

FlexMom_high_Cr <- lm(delta_C_high ~  lag_delta_C + lag_delta_C_squared + lag2_delta_C_squared,data = Merged_data)
summary(FlexMom_high_Cr)

```

```{r filtered data test}


adjusted_data <- Merged_data[1:1350,]
#summary(adjusted_data)


FlexMom_Dl <-lm(delta_D ~  lag_delta_D + lag_delta_D_squared + lag2_delta_D_squared,data = adjusted_data)
FlexMom_high_Dl <- lm(delta_D_high ~  lag_delta_D + lag_delta_D_squared + lag2_delta_D_squared,data = adjusted_data)

summary(FlexMom_Dl)

summary(FlexMom_high_Dl)

FlexMom_Cr <- lm(delta_C ~  lag_delta_C + lag_delta_C_squared + lag2_delta_C_squared,data = adjusted_data)

FlexMom_high_Cr <- lm(delta_C_high ~  lag_delta_C + lag_delta_C_squared + lag2_delta_C_squared,data = adjusted_data)
summary(FlexMom_high_Cr)


```
